#define USELUA

using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.IO;

using Barotrauma;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Graphics;
using HarmonyLib;
using MoonSharp.Interpreter;

namespace QICrabUI
{
  public class CUIInternalAttribute : System.Attribute { }
  [CUIInternal]
  public class CUILuaRegistrar
  {
    public static string CUITypesFile => Path.Combine(CUI.LuaFolder, "CUITypes.lua");

    public static bool IsRealCUIType(Type T)
    {
      if (T.DeclaringType != null) return false; // nested type
      if (T.Name == "<>c") return false; // guh
      if (T.IsGenericType) return false; // in lua?
      if (T.IsInterface) return false;
      if (T.IsSubclassOf(typeof(Attribute))) return false;
      if (Attribute.IsDefined(T, typeof(CUIInternalAttribute))) return false;
      if (typeof(CUILuaRegistrar).Namespace != T.Namespace) return false;
      return true;
    }



#if !USELUA
    [Conditional("DONT")]
#endif
    public void Register()
    {
      if (CUI.LuaFolder == null) return;
      if (!Directory.Exists(CUI.LuaFolder) || !CUI.UseLua) return;

      Assembly thisAssembly = Assembly.GetAssembly(typeof(CUILuaRegistrar));

      foreach (Type T in thisAssembly.GetTypes().Where(IsRealCUIType))
      {
        UserData.RegisterType(T);
      }

      RegisterActionConverter<CUIInput>();
      RegisterActionConverter<float, float>();
      RegisterActionConverter<TextInputEventArgs>();
      RegisterActionConverter<string>();
      RegisterActionConverter<CUIComponent>();
      RegisterActionConverter<bool>();
      RegisterActionConverter<CUIComponent, int>();


      UserData.RegisterType(typeof(CUI));
      var script = LuaCsSetup.Instance.LuaScriptManagementService.InternalScript;
      if (script != null)
      {
        script.Globals[nameof(CUI)] = UserData.CreateStatic(typeof(CUI));
      }

      ConstructLuaStaticsFile();
    }

    private void RegisterActionConverter<T>()
    {
      Script.GlobalOptions.CustomConverters.SetScriptToClrCustomConversion(DataType.Function, typeof(Action<T>), v =>
      {
        var function = v.Function;
        return (Action<T>)(p => LuaCsSetup.Instance.CallLuaFunction(function, p));
      });

      Script.GlobalOptions.CustomConverters.SetScriptToClrCustomConversion(DataType.ClrFunction, typeof(Action<T>), v =>
      {
        var function = v.Function;
        return (Action<T>)(p => LuaCsSetup.Instance.CallLuaFunction(function, p));
      });
    }

    private void RegisterActionConverter<T1, T2>()
    {
      Script.GlobalOptions.CustomConverters.SetScriptToClrCustomConversion(DataType.Function, typeof(Action<T1, T2>), v =>
      {
        var function = v.Function;
        return (Action<T1, T2>)((a1, a2) => LuaCsSetup.Instance.CallLuaFunction(function, a1, a2));
      });

      Script.GlobalOptions.CustomConverters.SetScriptToClrCustomConversion(DataType.ClrFunction, typeof(Action<T1, T2>), v =>
      {
        var function = v.Function;
        return (Action<T1, T2>)((a1, a2) => LuaCsSetup.Instance.CallLuaFunction(function, a1, a2));
      });
    }

#if !USELUA
    [Conditional("DONT")]
#endif
    public void Deregister()
    {
      try
      {
        var script = LuaCsSetup.Instance.LuaScriptManagementService.InternalScript;
        if (script != null)
        {
          script.Globals[nameof(CUI)] = null;
        }
      }
      catch (Exception e)
      {
        CUI.Error(e);
      }
    }

    public void ConstructLuaStaticsFile()
    {
      if (!Directory.Exists(CUI.LuaFolder)) return;

      Assembly thisAssembly = Assembly.GetAssembly(typeof(CUILuaRegistrar));

      string content = "-- This file is autogenerated\n";

      foreach (Type T in thisAssembly.GetTypes().Where(IsRealCUIType))
      {
        content += $"{T.Name} = UserData.CreateStatic(typeof({T.FullName}))\n";
      }

      using (StreamWriter writer = new StreamWriter(CUITypesFile, false))
      {
        writer.Write(content);
      }
    }
  }
}